const mongoose = require('mongoose');

/**
 * Paper Model
 * Stores academic paper information
 * Aggregates data from multiple external sources (OpenAlex, Semantic Scholar, Crossref)
 */

const paperSchema = new mongoose.Schema(
  {
    // Core Paper Information
    title: {
      type: String,
      required: [true, 'Paper title is required'],
      index: true,
    },
    abstract: {
      type: String,
      maxlength: 5000,
    },
    doi: {
      type: String,
      sparse: true,
      index: true,
    },
    publishedDate: {
      type: Date,
      index: true,
    },
    publicationYear: {
      type: Number,
      index: true,
    },
    publicationMonth: {
      type: Number,
      min: 1,
      max: 12,
    },

    // Source Identifiers (for deduplication and tracking)
    externalIds: {
      openalex: String,
      semanticScholar: String,
      crossref: String,
      ieee: String,
      exa: String,
      pubmed: String,
    },

    // Authors
    authors: [{
      authorId: { type: mongoose.Schema.Types.ObjectId, ref: 'Author', default: null },
      name: String,
      affiliations: [String],
      externalId: String,
      order: Number,
    }],

    // Journal Information
    journal: {
      type: mongoose.Schema.Types.ObjectId,
      ref: 'Journal',
    },
    journalName: String,
    journalIssn: String,

    // Citation Metrics
    citationCount: {
      type: Number,
      default: 0,
    },
    openAccessUrl: String,

    // Keywords & Topics
    keywords: [String],
    keywordIds: [{
      type: mongoose.Schema.Types.ObjectId,
      ref: 'Keyword',
    }],
    topics: [{
      type: mongoose.Schema.Types.ObjectId,
      ref: 'Topic',
    }],

    // AI-Generated Content
    aiSummary: String, // Generated by AI service
    aiKeywords: [String], // Extracted by AI service
    semanticEmbedding: [Number], // Vector representation (for similarity search)

    // Metadata
    source: {
      type: String,
      enum: ['openalex', 'semantic_scholar', 'crossref', 'ieee', 'exa'],
      required: true,
    },
    url: String,
    pdfUrl: String,
    uploadedPdf: {
      originalName: String,
      fileName: String,
      mimeType: String,
      size: Number,
      path: String,
      url: String,
      uploadedBy: {
        type: mongoose.Schema.Types.ObjectId,
        ref: 'User',
        default: null,
      },
      uploadedAt: Date,
      textExtracted: {
        type: Boolean,
        default: false,
      },
      extractionError: String,
    },
    fullText: {
      type: String,
      maxlength: 200000,
    },

    // Relevance & Ranking
    relevanceScore: {
      type: Number,
      default: 0,
    },
    trendScore: {
      type: Number,
      default: 0,
    },

    // User Data
    bookmarkedBy: [{
      type: mongoose.Schema.Types.ObjectId,
      ref: 'User',
    }],
    viewCount: {
      type: Number,
      default: 0,
    },

    // Sync Status
    lastSyncedAt: Date,

    // Corpus (AnalysisRun snapshot)
    analysisRunId: {
      type: mongoose.Schema.Types.ObjectId,
      ref: 'AnalysisRun',
      index: true,
      default: null,
    },
  },
  { timestamps: true }
);

paperSchema.index(
  { analysisRunId: 1, 'externalIds.openalex': 1 },
  { unique: true, sparse: true }
);

// Index for full-text search
paperSchema.index({ title: 'text', abstract: 'text' });

// Index for date-based queries
paperSchema.index({ publicationYear: -1 });
paperSchema.index({ keywordIds: 1 });

// Index for trending papers
paperSchema.index({ citationCount: -1, publishedDate: -1 });

module.exports = mongoose.model('Paper', paperSchema);
