const mongoose = require('mongoose');

/**
 * Topic Model
 * Stores AI-detected research topics and their trends
 * Generated by BERTopic clustering in AI service
 */

const topicSchema = new mongoose.Schema(
  {
    name: {
      type: String,
      required: true,
      index: true,
    },
    analysisRunId: {
      type: mongoose.Schema.Types.ObjectId,
      ref: 'AnalysisRun',
      default: null,
      index: true,
    },
    seedKeyword: String,
    description: String,
    relatedKeywords: [String],
    
    // Trend Information
    paperCount: {
      type: Number,
      default: 0,
    },
    
    // Trend Status
    trendStatus: {
      type: String,
      enum: ['exploding', 'growing', 'stable', 'declining'],
      default: 'stable',
    },
    
    // Growth Metrics
    growthRate: {
      type: Number,
      default: 0,
    },
    accelerationFactor: {
      type: Number,
      default: 0,
    },
    
    // Timeline Data (for trend visualization)
    yearlyData: [{
      year: Number,
      count: Number,
      growthRate: Number,
    }],
    
    // Relationships
    parentTopics: [{
      type: mongoose.Schema.Types.ObjectId,
      ref: 'Topic',
    }],
    relatedTopics: [{
      type: mongoose.Schema.Types.ObjectId,
      ref: 'Topic',
    }],
    
    // Emerging Topic Detection
    isEmerging: Boolean,
    emergenceScore: Number, // 0-1 score indicating how new/emerging
    
    papers: [{
      type: mongoose.Schema.Types.ObjectId,
      ref: 'Paper',
    }],
    
    lastAnalyzedAt: Date,
  },
  { timestamps: true }
);

module.exports = mongoose.model('Topic', topicSchema);
